title: 3D printable shoe charm
hero_image: images/banner.png
description: Design a shoe charm that can be 3D printed.
version: 1
theme: turquoise
duration: 2
listed: true
copyedit: true
last_tested: "2025-07-31"
steps:
- title: What you will make
- title: Create a new project
  completion:
  - engaged
- title: Create a button
- title: Create a cutout
  completion:
  - internal
- title: 3D print your charm
- title: Challenge
  challenge: true
  completion:
  - external
